version: 2
updates:
  - package-ecosystem: npm
    directory: /Section_28 API/5.5 Secrets Project
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: /Section_30 Build API/6.0 DIY API
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: /Section_30 Build API/6.1 Blog API Project
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Section_28 API/5.2 Axios"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Section_28 API/5.3 API Authentication"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Section_28 API/5.4 REST APIs"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Section_25 EJS/4.1 EJS Tags"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Section_25 EJS/4.2+Passing+Data"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Section_25 EJS/4.3 EJS Partials"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Section_25 EJS/4.4 Band Generator Project"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Section_28 API/5.1 JSON"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
